Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tstat # your work here
tvar=t.interval(0.95,degrees_of_freedom)[1]
Answer # = 'yes' or 'no'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_1659/4010596980.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mtstat[0m [0;31m# your work here[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mtvar[0m[0;34m=[0m[0mt[0m[0;34m.[0m[0minterval[0m[0;34m([0m[0;36m0.95[0m[0;34m,[0m[0mdegrees_of_freedom[0m[0;34m)[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mAnswer[0m [0;31m# = 'yes' or 'no'[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'degrees_of_freedom' is not defined
NameError: name 'degrees_of_freedom' is not defined

